baseurl:
url: http://www.lifestonechurch.net
description: A Bible-based church in Herriman, Utah.
markdown: kramdown
managerName: Adam Harris
managerEmail: adam@mountainview-webdesign.com
title: Lifestone Church
organizationName: Lifestone Church
squareLogo: http://www.lifestonechurch.net/assets/images/logo2.jpg
podcastSubtitle: Messages from Sunday morning worship at Lifestone Church
permalink: /:categories/:title/
google_analytics_code: UA-44899328-1
collections:
  layout: redirect
  redirects:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect
  -
    scope:
      type: posts
    values:
      layout: sermon
      categories:
        - media
        - sermons
